version: "3.5"
services:
  mysql:
    image: mysql:latest
    container_name: register_api_mysql
    command: --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  register_api:
    container_name: "register_api"
    build: .
    ports:
      - "8000:8000"
    command: ["/code/sh/wait-for-it.sh", "mysql:3306", "--strict" , "--timeout=300", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    restart: on-failure
    volumes:
      - ./app:/code/app/
      - ./sh:/code/sh/
      - ./tests:/code/tests/
      - ./.env:/code/.env
    links: 
        - mysql